-- Extend GPU item type with specs aligned to NVIDIA product comparison tables.

INSERT INTO spec_sections (id, item_type_id, name, "order") VALUES
  ('sec-gpu-memory', 'type-gpu', 'Memory', 5),
  ('sec-gpu-technology', 'type-gpu', 'Technology', 6),
  ('sec-gpu-display', 'type-gpu', 'Display', 7),
  ('sec-gpu-dimensions', 'type-gpu', 'Dimensions', 8);

INSERT INTO specs (id, item_type_id, section_id, label, type, required, is_archived, "order", rating_min, rating_max, value_preference) VALUES
  ('spec-gpu-memory-config', 'type-gpu', 'sec-gpu-memory', 'Memory config', 'text', 0, 0, 1, NULL, NULL, NULL),
  ('spec-gpu-memory-bus', 'type-gpu', 'sec-gpu-memory', 'Memory interface', 'text', 0, 0, 2, NULL, NULL, NULL),
  ('spec-gpu-base-clock', 'type-gpu', 'sec-gpu-performance', 'Base clock (MHz)', 'number', 0, 0, 4, NULL, NULL, 'higher'),
  ('spec-gpu-rt-gen', 'type-gpu', 'sec-gpu-performance', 'Ray tracing cores', 'text', 0, 0, 5, NULL, NULL, NULL),
  ('spec-gpu-tensor-gen', 'type-gpu', 'sec-gpu-performance', 'Tensor cores', 'text', 0, 0, 6, NULL, NULL, NULL),
  ('spec-gpu-architecture', 'type-gpu', 'sec-gpu-technology', 'Architecture', 'select', 0, 0, 1, NULL, NULL, NULL),
  ('spec-gpu-dlss', 'type-gpu', 'sec-gpu-technology', 'DLSS', 'text', 0, 0, 2, NULL, NULL, NULL),
  ('spec-gpu-reflex', 'type-gpu', 'sec-gpu-technology', 'NVIDIA Reflex', 'boolean', 0, 0, 3, NULL, NULL, NULL),
  ('spec-gpu-broadcast', 'type-gpu', 'sec-gpu-technology', 'NVIDIA Broadcast', 'boolean', 0, 0, 4, NULL, NULL, NULL),
  ('spec-gpu-pcie-gen4', 'type-gpu', 'sec-gpu-technology', 'PCI Express Gen 4', 'boolean', 0, 0, 5, NULL, NULL, NULL),
  ('spec-gpu-resizable-bar', 'type-gpu', 'sec-gpu-technology', 'Resizable BAR', 'boolean', 0, 0, 6, NULL, NULL, NULL),
  ('spec-gpu-geforce-experience', 'type-gpu', 'sec-gpu-technology', 'GeForce Experience', 'boolean', 0, 0, 7, NULL, NULL, NULL),
  ('spec-gpu-freestyle', 'type-gpu', 'sec-gpu-technology', 'NVIDIA FreeStyle', 'boolean', 0, 0, 8, NULL, NULL, NULL),
  ('spec-gpu-shadowplay', 'type-gpu', 'sec-gpu-technology', 'NVIDIA ShadowPlay', 'boolean', 0, 0, 9, NULL, NULL, NULL),
  ('spec-gpu-highlights', 'type-gpu', 'sec-gpu-technology', 'NVIDIA Highlights', 'boolean', 0, 0, 10, NULL, NULL, NULL),
  ('spec-gpu-gsync', 'type-gpu', 'sec-gpu-technology', 'NVIDIA G-SYNC', 'boolean', 0, 0, 11, NULL, NULL, NULL),
  ('spec-gpu-game-ready-drivers', 'type-gpu', 'sec-gpu-technology', 'Game Ready Drivers', 'boolean', 0, 0, 12, NULL, NULL, NULL),
  ('spec-gpu-studio-drivers', 'type-gpu', 'sec-gpu-technology', 'NVIDIA Studio Drivers', 'boolean', 0, 0, 13, NULL, NULL, NULL),
  ('spec-gpu-omniverse', 'type-gpu', 'sec-gpu-technology', 'NVIDIA Omniverse', 'boolean', 0, 0, 14, NULL, NULL, NULL),
  ('spec-gpu-dx12-ultimate', 'type-gpu', 'sec-gpu-technology', 'DirectX 12 Ultimate', 'boolean', 0, 0, 15, NULL, NULL, NULL),
  ('spec-gpu-gpu-boost', 'type-gpu', 'sec-gpu-technology', 'NVIDIA GPU Boost', 'boolean', 0, 0, 16, NULL, NULL, NULL),
  ('spec-gpu-nvlink', 'type-gpu', 'sec-gpu-technology', 'NVIDIA NVLink (SLI)', 'boolean', 0, 0, 17, NULL, NULL, NULL),
  ('spec-gpu-vulkan-opengl', 'type-gpu', 'sec-gpu-technology', 'Vulkan RT / OpenGL 4.6', 'boolean', 0, 0, 18, NULL, NULL, NULL),
  ('spec-gpu-nvenc', 'type-gpu', 'sec-gpu-technology', 'NVIDIA Encoder (NVENC)', 'text', 0, 0, 19, NULL, NULL, NULL),
  ('spec-gpu-nvdec', 'type-gpu', 'sec-gpu-technology', 'NVIDIA Decoder (NVDEC)', 'text', 0, 0, 20, NULL, NULL, NULL),
  ('spec-gpu-av1-encode', 'type-gpu', 'sec-gpu-technology', 'AV1 Encode', 'boolean', 0, 0, 21, NULL, NULL, NULL),
  ('spec-gpu-av1-decode', 'type-gpu', 'sec-gpu-technology', 'AV1 Decode', 'boolean', 0, 0, 22, NULL, NULL, NULL),
  ('spec-gpu-cuda-capability', 'type-gpu', 'sec-gpu-technology', 'CUDA capability', 'number', 0, 0, 23, NULL, NULL, 'higher'),
  ('spec-gpu-vr-ready', 'type-gpu', 'sec-gpu-technology', 'VR Ready', 'boolean', 0, 0, 24, NULL, NULL, NULL),
  ('spec-gpu-max-resolution', 'type-gpu', 'sec-gpu-display', 'Maximum display resolution', 'text', 0, 0, 1, NULL, NULL, NULL),
  ('spec-gpu-display-connectors', 'type-gpu', 'sec-gpu-display', 'Display connectors', 'text', 0, 0, 2, NULL, NULL, NULL),
  ('spec-gpu-multi-monitor', 'type-gpu', 'sec-gpu-display', 'Multi monitor', 'text', 0, 0, 3, NULL, NULL, NULL),
  ('spec-gpu-hdcp', 'type-gpu', 'sec-gpu-display', 'HDCP', 'text', 0, 0, 4, NULL, NULL, NULL),
  ('spec-gpu-length', 'type-gpu', 'sec-gpu-dimensions', 'Length', 'text', 0, 0, 1, NULL, NULL, NULL),
  ('spec-gpu-width', 'type-gpu', 'sec-gpu-dimensions', 'Width', 'text', 0, 0, 2, NULL, NULL, NULL),
  ('spec-gpu-slots', 'type-gpu', 'sec-gpu-dimensions', 'Slots', 'text', 0, 0, 3, NULL, NULL, NULL),
  ('spec-gpu-max-temp', 'type-gpu', 'sec-gpu-power', 'Max GPU temperature (°C)', 'number', 0, 0, 3, NULL, NULL, 'lower'),
  ('spec-gpu-idle-power', 'type-gpu', 'sec-gpu-power', 'Idle power (W)', 'number', 0, 0, 4, NULL, NULL, 'lower'),
  ('spec-gpu-video-power', 'type-gpu', 'sec-gpu-power', 'Video playback power (W)', 'number', 0, 0, 5, NULL, NULL, 'lower'),
  ('spec-gpu-gaming-power', 'type-gpu', 'sec-gpu-power', 'Average gaming power (W)', 'number', 0, 0, 6, NULL, NULL, 'lower'),
  ('spec-gpu-power-connectors', 'type-gpu', 'sec-gpu-power', 'Supplementary power connectors', 'text', 0, 0, 7, NULL, NULL, NULL);

INSERT INTO spec_options (id, spec_id, label, value, "order") VALUES
  ('opt-gpu-arch-ada', 'spec-gpu-architecture', 'Ada Lovelace', 'ada-lovelace', 1),
  ('opt-gpu-arch-ampere', 'spec-gpu-architecture', 'Ampere', 'ampere', 2),
  ('opt-gpu-arch-hopper', 'spec-gpu-architecture', 'Hopper', 'hopper', 3),
  ('opt-gpu-arch-blackwell', 'spec-gpu-architecture', 'Blackwell', 'blackwell', 4);
